### ISSUE TITLE
012 | Som en användare vill jag kunna se betyg och recensioner på produkten

### ISSUE THREAD

**Issue by Camilla-bjorkcom** [Projekt-Grupp-2/RikaWebApp#46]
**Tasks:** Camilla
- [ ] Skapa komponent "Review"
- [ ] Lägg till fontawesome ikoner för gul stjärna resp. tom stjärna
- [ ] Skapa databas för produktens recensioner och betyg
- [ ] Använd data från productprovider ("antal reviews", "betyg")
- [ ] Loopa igenom antal stjärnor (1-5) och rendera ut i komponenten
- [ ] Rendera ut "antal reviews"

**Aktivitets Diagram: Anna**
![Image](https://github.com/user-attachments/assets/29464a38-51ef-4066-977e-78b824aaaba6)

**Sekvens Diagram:**

**Acceptance Kriterier:**

**Testfallsbeskrivning:**
